// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ParkPass.iOS.ParkWebService {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="ParkPass.iOS.ParkWebService", ConfigurationName="ParkasmxWebServiceSoap")]
public interface ParkasmxWebServiceSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/getAll")]
    System.Collections.Generic.List<tempuri.org.Park> getAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/getAll", AsyncPattern=true)]
    System.IAsyncResult BegingetAll(System.AsyncCallback asyncCallback, object userState);
    
    System.Collections.Generic.List<tempuri.org.Park> EndgetAll(System.IAsyncResult result);
}

public interface ParkasmxWebServiceSoapChannel : ParkasmxWebServiceSoap, System.ServiceModel.IClientChannel {
}

public class ParkasmxWebServiceSoapClient : System.ServiceModel.ClientBase<ParkasmxWebServiceSoap>, ParkasmxWebServiceSoap {
    
    private BeginOperationDelegate onBegingetAllDelegate;
    
    private EndOperationDelegate onEndgetAllDelegate;
    
    private System.Threading.SendOrPostCallback ongetAllCompletedDelegate;
    
    public ParkasmxWebServiceSoapClient() {
    }
    
    public ParkasmxWebServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public ParkasmxWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ParkasmxWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public ParkasmxWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public event System.EventHandler<getAllCompletedEventArgs> getAllCompleted;
    
    public System.Collections.Generic.List<tempuri.org.Park> getAll() {
        return base.Channel.getAll();
    }
    
    public System.IAsyncResult BegingetAll(System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BegingetAll(asyncCallback, userState);
    }
    
    public System.Collections.Generic.List<tempuri.org.Park> EndgetAll(System.IAsyncResult result) {
        return base.Channel.EndgetAll(result);
    }
    
    private System.IAsyncResult OnBegingetAll(object[] args, System.AsyncCallback asyncCallback, object userState) {
        return this.BegingetAll(asyncCallback, userState);
    }
    
    private object[] OnEndgetAll(System.IAsyncResult result) {
        object __ret = this.EndgetAll(result);
        return new object[] {
                __ret};
    }
    
    private void OngetAllCompleted(object state) {
        if ((this.getAllCompleted != null)) {
            InvokeAsyncCompletedEventArgs args = ((InvokeAsyncCompletedEventArgs)(state));
            this.getAllCompleted(this, new getAllCompletedEventArgs(args.Results, args.Error, args.Cancelled, args.UserState));
        }
    }
    
    public void getAllAsync() {
        this.getAllAsync(null);
    }
    
    public void getAllAsync(object userState) {
        if ((this.onBegingetAllDelegate == null)) {
            this.onBegingetAllDelegate = new BeginOperationDelegate(this.OnBegingetAll);
        }
        if ((this.onEndgetAllDelegate == null)) {
            this.onEndgetAllDelegate = new EndOperationDelegate(this.OnEndgetAll);
        }
        if ((this.ongetAllCompletedDelegate == null)) {
            this.ongetAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllCompleted);
        }
        base.InvokeAsync(this.onBegingetAllDelegate, new object[] {
                    userState}, this.onEndgetAllDelegate, this.ongetAllCompletedDelegate, userState);
    }
}

public class getAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    public getAllCompletedEventArgs(object[] results, System.Exception error, bool cancelled, object userState) : 
            base(error, cancelled, userState) {
        this.results = results;
    }
    
    public System.Collections.Generic.List<tempuri.org.Park> Result {
        get {
            return ((System.Collections.Generic.List<tempuri.org.Park>)(this.results[0]));
        }
    }
}
namespace tempuri.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getAll", Namespace="http://tempuri.org/")]
    public partial class getAll : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getAllResponse", Namespace="http://tempuri.org/")]
    public partial class getAllResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<tempuri.org.Park> getAllResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<tempuri.org.Park> getAllResult {
            get {
                return this.getAllResultField;
            }
            set {
                this.getAllResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Park", Namespace="http://tempuri.org/")]
    public partial class Park : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private string NameField;
        
        private string AddressField;
        
        private string CityField;
        
        private string StateField;
        
        private int ZipcodeField;
        
        private string ParkDescriptionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                this.ZipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ParkDescription {
            get {
                return this.ParkDescriptionField;
            }
            set {
                this.ParkDescriptionField = value;
            }
        }
    }
}
