// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ParkPass.www.w3schools.com {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="ParkPass.www.w3schools.com", ConfigurationName="TempConvertSoap")]
public interface TempConvertSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/xml/FahrenheitToCelsius")]
    string FahrenheitToCelsius(string Fahrenheit);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/xml/FahrenheitToCelsius", AsyncPattern=true)]
    System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback asyncCallback, object userState);
    
    string EndFahrenheitToCelsius(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/xml/CelsiusToFahrenheit")]
    string CelsiusToFahrenheit(string Celsius);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.w3schools.com/xml/CelsiusToFahrenheit", AsyncPattern=true)]
    System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback asyncCallback, object userState);
    
    string EndCelsiusToFahrenheit(System.IAsyncResult result);
}

public interface TempConvertSoapChannel : TempConvertSoap, System.ServiceModel.IClientChannel {
}

public class TempConvertSoapClient : System.ServiceModel.ClientBase<TempConvertSoap>, TempConvertSoap {
    
    private BeginOperationDelegate onBeginFahrenheitToCelsiusDelegate;
    
    private EndOperationDelegate onEndFahrenheitToCelsiusDelegate;
    
    private System.Threading.SendOrPostCallback onFahrenheitToCelsiusCompletedDelegate;
    
    private BeginOperationDelegate onBeginCelsiusToFahrenheitDelegate;
    
    private EndOperationDelegate onEndCelsiusToFahrenheitDelegate;
    
    private System.Threading.SendOrPostCallback onCelsiusToFahrenheitCompletedDelegate;
    
    public TempConvertSoapClient() {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public TempConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public event System.EventHandler<FahrenheitToCelsiusCompletedEventArgs> FahrenheitToCelsiusCompleted;
    
    public event System.EventHandler<CelsiusToFahrenheitCompletedEventArgs> CelsiusToFahrenheitCompleted;
    
    public string FahrenheitToCelsius(string Fahrenheit) {
        return base.Channel.FahrenheitToCelsius(Fahrenheit);
    }
    
    public System.IAsyncResult BeginFahrenheitToCelsius(string Fahrenheit, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginFahrenheitToCelsius(Fahrenheit, asyncCallback, userState);
    }
    
    public string EndFahrenheitToCelsius(System.IAsyncResult result) {
        return base.Channel.EndFahrenheitToCelsius(result);
    }
    
    public string CelsiusToFahrenheit(string Celsius) {
        return base.Channel.CelsiusToFahrenheit(Celsius);
    }
    
    public System.IAsyncResult BeginCelsiusToFahrenheit(string Celsius, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginCelsiusToFahrenheit(Celsius, asyncCallback, userState);
    }
    
    public string EndCelsiusToFahrenheit(System.IAsyncResult result) {
        return base.Channel.EndCelsiusToFahrenheit(result);
    }
    
    private System.IAsyncResult OnBeginFahrenheitToCelsius(object[] args, System.AsyncCallback asyncCallback, object userState) {
        string Fahrenheit = ((string)(args[0]));
        return this.BeginFahrenheitToCelsius(Fahrenheit, asyncCallback, userState);
    }
    
    private object[] OnEndFahrenheitToCelsius(System.IAsyncResult result) {
        object __ret = this.EndFahrenheitToCelsius(result);
        return new object[] {
                __ret};
    }
    
    private void OnFahrenheitToCelsiusCompleted(object state) {
        if ((this.FahrenheitToCelsiusCompleted != null)) {
            InvokeAsyncCompletedEventArgs args = ((InvokeAsyncCompletedEventArgs)(state));
            this.FahrenheitToCelsiusCompleted(this, new FahrenheitToCelsiusCompletedEventArgs(args.Results, args.Error, args.Cancelled, args.UserState));
        }
    }
    
    public void FahrenheitToCelsiusAsync(string Fahrenheit) {
        this.FahrenheitToCelsiusAsync(Fahrenheit, null);
    }
    
    public void FahrenheitToCelsiusAsync(string Fahrenheit, object userState) {
        if ((this.onBeginFahrenheitToCelsiusDelegate == null)) {
            this.onBeginFahrenheitToCelsiusDelegate = new BeginOperationDelegate(this.OnBeginFahrenheitToCelsius);
        }
        if ((this.onEndFahrenheitToCelsiusDelegate == null)) {
            this.onEndFahrenheitToCelsiusDelegate = new EndOperationDelegate(this.OnEndFahrenheitToCelsius);
        }
        if ((this.onFahrenheitToCelsiusCompletedDelegate == null)) {
            this.onFahrenheitToCelsiusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFahrenheitToCelsiusCompleted);
        }
        base.InvokeAsync(this.onBeginFahrenheitToCelsiusDelegate, new object[] {
                    Fahrenheit,
                    userState}, this.onEndFahrenheitToCelsiusDelegate, this.onFahrenheitToCelsiusCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginCelsiusToFahrenheit(object[] args, System.AsyncCallback asyncCallback, object userState) {
        string Celsius = ((string)(args[0]));
        return this.BeginCelsiusToFahrenheit(Celsius, asyncCallback, userState);
    }
    
    private object[] OnEndCelsiusToFahrenheit(System.IAsyncResult result) {
        object __ret = this.EndCelsiusToFahrenheit(result);
        return new object[] {
                __ret};
    }
    
    private void OnCelsiusToFahrenheitCompleted(object state) {
        if ((this.CelsiusToFahrenheitCompleted != null)) {
            InvokeAsyncCompletedEventArgs args = ((InvokeAsyncCompletedEventArgs)(state));
            this.CelsiusToFahrenheitCompleted(this, new CelsiusToFahrenheitCompletedEventArgs(args.Results, args.Error, args.Cancelled, args.UserState));
        }
    }
    
    public void CelsiusToFahrenheitAsync(string Celsius) {
        this.CelsiusToFahrenheitAsync(Celsius, null);
    }
    
    public void CelsiusToFahrenheitAsync(string Celsius, object userState) {
        if ((this.onBeginCelsiusToFahrenheitDelegate == null)) {
            this.onBeginCelsiusToFahrenheitDelegate = new BeginOperationDelegate(this.OnBeginCelsiusToFahrenheit);
        }
        if ((this.onEndCelsiusToFahrenheitDelegate == null)) {
            this.onEndCelsiusToFahrenheitDelegate = new EndOperationDelegate(this.OnEndCelsiusToFahrenheit);
        }
        if ((this.onCelsiusToFahrenheitCompletedDelegate == null)) {
            this.onCelsiusToFahrenheitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCelsiusToFahrenheitCompleted);
        }
        base.InvokeAsync(this.onBeginCelsiusToFahrenheitDelegate, new object[] {
                    Celsius,
                    userState}, this.onEndCelsiusToFahrenheitDelegate, this.onCelsiusToFahrenheitCompletedDelegate, userState);
    }
}

public class FahrenheitToCelsiusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    public FahrenheitToCelsiusCompletedEventArgs(object[] results, System.Exception error, bool cancelled, object userState) : 
            base(error, cancelled, userState) {
        this.results = results;
    }
    
    public string Result {
        get {
            return ((string)(this.results[0]));
        }
    }
}

public class CelsiusToFahrenheitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    public CelsiusToFahrenheitCompletedEventArgs(object[] results, System.Exception error, bool cancelled, object userState) : 
            base(error, cancelled, userState) {
        this.results = results;
    }
    
    public string Result {
        get {
            return ((string)(this.results[0]));
        }
    }
}
namespace www.w3schools.com.xml {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FahrenheitToCelsius", Namespace="http://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsius : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FahrenheitField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fahrenheit {
            get {
                return this.FahrenheitField;
            }
            set {
                this.FahrenheitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FahrenheitToCelsiusResponse", Namespace="http://www.w3schools.com/xml/")]
    public partial class FahrenheitToCelsiusResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FahrenheitToCelsiusResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FahrenheitToCelsiusResult {
            get {
                return this.FahrenheitToCelsiusResultField;
            }
            set {
                this.FahrenheitToCelsiusResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CelsiusToFahrenheit", Namespace="http://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheit : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CelsiusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Celsius {
            get {
                return this.CelsiusField;
            }
            set {
                this.CelsiusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CelsiusToFahrenheitResponse", Namespace="http://www.w3schools.com/xml/")]
    public partial class CelsiusToFahrenheitResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CelsiusToFahrenheitResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CelsiusToFahrenheitResult {
            get {
                return this.CelsiusToFahrenheitResultField;
            }
            set {
                this.CelsiusToFahrenheitResultField = value;
            }
        }
    }
}
